---
kind: pipeline
type: docker
name: Building..
steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: smartinfrasolutions/unimus
    tags: [ "latest" ]
    username: smartinfrasolutions
    password:
      from_secret: dockerhub_token
- name: notification
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [success, failure]
---
kind: signature
hmac: 85c88210c2e85bc343147b34e1d82971fb2f7d3a3fb7ee33521566f54255c494

...
