---
kind: pipeline
type: docker
name: Building..
node:
  drone: bzkg9
steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: smartinfrasolutions/unimus
    tags: [ "latest" ]
    username: smartinfrasolutions
    password:
      from_secret: dockerhub_token
- name: notification
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [success, failure]
---
kind: signature
hmac: b257bef1dc2c7df5e588f5ed59a08999a01683010099be4a5082332e11b698f5

...
