---
kind: pipeline
type: docker
name: Building..
node:
  drone: nimi
steps:
- name: build & push
  image: plugins/docker
  settings:
    repo: smartinfrasolutions/unimus
    tags: [ "latest" ]
    username: smartinfrasolutions
    password:
      from_secret: dockerhub_token
- name: notification
  image: plugins/webhook
  settings:
    urls:
      from_secret: webhookgotify
    content_type: application/json
    template: |
      {
       "message": "{{ repo.owner }} as updated {{ repo.name }} with {{ build.status }}.",
       "priority": 4,
       "title": "{{ repo.name }} build"
      }
  when:
    status: [success, failure]
---
kind: signature
hmac: 48f035677f8054418da93e826e1273ec0cadefaa27c7e39adffa32e4d7d09c4f

...
