FROM alpine:3.17

# Set Unimus lated download url
ENV DOWNLOAD_URL https://download.unimus.net/unimus/-%20Latest/Unimus.jar

# Update & install
RUN apk update \
    && apk add --no-cache less curl wget tzdata openjdk11-jre-headless \
    && rm -rf /var/cache/apk/*

# Unimus binary download
RUN curl -L -o /opt/unimus.jar $DOWNLOAD_URL

# Copy all files (start.sh) into the container image
COPY files/* /opt/

# add script permission
RUN chmod +x /opt/start.sh

# Entrypoint
ENTRYPOINT ["/opt/start.sh"]
