FROM debian:stable-slim

# Set Unimus lated download url
ENV DOWNLOAD_URL=https://download.unimus.net/unimus/-%20Latest/Unimus.jar

# Update & install
RUN apt-get update && \
    apt-get install -y dialog curl tini less wget tzdata openjdk-17-jre-headless iputils-ping && \
    apt-get clean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

# Unimus binary download
RUN curl -L -o /opt/unimus.jar $DOWNLOAD_URL

# Copy all files (start.sh) into the container image
COPY files/* /opt/

# Add script permission
RUN chmod +x /opt/start.sh

# Entrypoint
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/opt/start.sh"]