FROM alpine:3.19

# Set Unimus lated download url
ENV DOWNLOAD_URL https://download.unimus.net/unimus/-%20Latest/Unimus.jar

# Update & install
RUN apk update && \
    apk add --no-cache tini less curl wget tzdata openjdk11-jre-headless-11.0.22_p7-r0 && \
    rm -rf /var/cache/apk/*

# Unimus binary download
RUN curl -L -o /opt/unimus.jar $DOWNLOAD_URL

# Copy all files (start.sh) into the container image
COPY files/* /opt/

# add script permission
RUN chmod +x /opt/start.sh

# Entrypoint
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/opt/start.sh"]