---
when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:3.1.0'
  - &platforms_alpine 'linux/arm64/v8,linux/amd64,linux/ppc64le'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username: smartinfrasolutions
        password:
          from_secret: docker_token
  - &publish_repos 'smartinfrasolutions/unimus'

steps:

  build-unimus-alpine-dev:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile-alpine
      platforms: *platforms_alpine
      tag: latest-alpine-dev
      logins: *publish_logins
    when:
      - event: [pull_request, push]

  build-unimus-alpine:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile-alpine
      platforms: *platforms_alpine
      tag: [latest, '${CI_COMMIT_TAG}-alpine-linux']
      logins: *publish_logins
    when:
      - event: tag
