---
when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx'
  - &platforms_debian 'linux/arm64/v8,linux/amd64,linux/ppc64le'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username: smartinfrasolutions
        password:
          from_secret: docker_token
  - &publish_repos 'smartinfrasolutions/unimus'

steps:

  build-unimus-debian-dev:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile-debian
      platforms: *platforms_debian
      tag: latest-debian-dev
      logins: *publish_logins
    when:
      - event: [pull_request, push]

  build-unimus-debian:
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile-debian
      platforms: *platforms_debian
      tag: [latest-debian, '${CI_COMMIT_TAG}-debian-linux']
      logins: *publish_logins
    when:
      - event: tag