when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:

  link-validation:
    image: docker.io/lycheeverse/lychee
    group: test
    commands:
      - lychee --no-progress --format detailed README.md

  pushrm-dockerhub:
    image: docker.io/chko/docker-pushrm:1
    secrets:
      - source: docker_token
        target: DOCKER_PASS
    environment:
      DOCKER_USER: smatinfrasolutions
      PUSHRM_FILE: README.md
      PUSHRM_SHORT: Rootless Alpine base image
      PUSHRM_TARGET: smartinfrasolutions/${CI_REPO_NAME}
