---
when:
  - event: [push, pull_request, tag]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &buildx_plugin 'woodpeckerci/plugin-docker-buildx'
  - &platforms_alpine 'linux/arm64/v8,linux/amd64'
  - publish_logins: &publish_logins
      - registry: https://index.docker.io/v1/
        username: smartinfrasolutions
        password:
          from_secret: docker_token
  - &publish_repos 'smartinfrasolutions/unimus'

steps:

  - name: build-unimus-alpine-dev
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile-alpine
      platforms: *platforms_alpine
      tag: [latest-alpine, 'dev-alpine-linux']
      logins: *publish_logins
    when:
      - event:
         - push

  - name: build-unimus-alpine-dev
    image: *buildx_plugin
    settings:
      repo: *publish_repos
      dockerfile: Dockerfile-alpine
      platforms: *platforms_alpine
      tag: [latest-alpine, '${CI_COMMIT_TAG}-alpine-linux']
      logins: *publish_logins
    when:
      - event: [pull_request, tag]
