---
depends_on: [alpine, debian]
when:
  - event: [pull_request, tag]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: link-validation
    image: docker.io/lycheeverse/lychee
    commands:
      - lychee --no-progress --format detailed README.md

  - name: pushrm-dockerhub
    image: docker.io/chko/docker-pushrm:1
    environment:
      DOCKER_USER: smartinfrasolutions
      PUSHRM_FILE: README.md
      PUSHRM_SHORT: Rootless Alpine & Debian images
      PUSHRM_TARGET: smartinfrasolutions/unimus
      DOCKER_PASS: 
        - from_secret: docker_token
    commands:
       - /bin/true